resources: 
  webhooks:
    - webhook: MyWebHook
      connection: WebHook-connection

  repositories:
    - repository: notification
      type: github
      name: maazpatel24/core-templates
      endpoint: maazpatel24-connection
      ref: main
      
trigger: none

variables:
  branchRef: '${{ parameters.MyWebHook.ref }}'
  repoName: '${{ parameters.MyWebHook.repository.full_name }}'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Stage 1 
  condition: eq( '$(repoName)', '$(Build.Repository.Name)')

  jobs:
  - job: 
    steps:  
      - script: |
          # echo ${{ parameters.MyWebHook.ref }}
          echo $(branchRef)
          echo $(repoName)
          echo $(Build.Repository.Name)
  # - template: notifications/senders.yml@notification
  #   parameters:
  #     message: "Hello world Maaz"
  #     senders:
  #     - Slack
  #     - MSTeams
  #     - OutLook