resources: 
  webhooks:
    - webhook: MyWebHook
      connection: WebHook-connection

  repositories:
    - repository: notification
      type: github
      name: maazpatel24/core-templates
      endpoint: maazpatel24-connection
      ref: main
      
trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - template: notifications/senders.yml@notification
    parameters:
      message: "Hello world Maaz"
      senders:
      - Slack
      - MSTeams
      - OutLook